name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "35 8 * * MON-FRI" # Every weekday at 08:35 UTC
jobs:
  security-kotlin-owasp-check:
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v2
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      nvd_feed_version: '2'
    secrets: inherit
